-- Migration: Add ai_generated column to elements table
-- Purpose: Track which content was generated by AI vs manual input
-- Date: 2025-08-15

-- Add ai_generated column to elements table
ALTER TABLE elements 
ADD COLUMN ai_generated BOOLEAN DEFAULT FALSE;

-- Add comment for documentation
COMMENT ON COLUMN elements.ai_generated IS 'Tracks whether this element content was generated by AI (TRUE) or created manually (FALSE)';

-- Create index for better query performance when filtering by AI generated content
CREATE INDEX idx_elements_ai_generated ON elements(ai_generated);

-- Optional: Update existing elements that might be AI generated
-- (This looks for AI placeholder content patterns)
UPDATE elements 
SET ai_generated = TRUE 
WHERE 
    content LIKE '%[AI Content:%' 
    OR content LIKE '%✨%'
    OR content LIKE '%AI zal dit vullen%'
    OR content LIKE '%Genereer%'
    OR content LIKE '%contentHint%';

-- Add RLS (Row Level Security) policy if needed
-- This ensures users can only see/modify their own project's elements
ALTER TABLE elements ENABLE ROW LEVEL SECURITY;

-- Policy for SELECT (users can view elements from their projects)
CREATE POLICY "Users can view elements from their projects" ON elements
    FOR SELECT USING (
        page_id IN (
            SELECT p.id FROM pages p 
            JOIN projects pr ON p.project_id = pr.id 
            WHERE pr.user_id = auth.uid()
        )
    );

-- Policy for UPDATE (users can update elements from their projects)
CREATE POLICY "Users can update elements from their projects" ON elements
    FOR UPDATE USING (
        page_id IN (
            SELECT p.id FROM pages p 
            JOIN projects pr ON p.project_id = pr.id 
            WHERE pr.user_id = auth.uid()
        )
    );

-- Policy for INSERT (users can insert elements into their projects)
CREATE POLICY "Users can insert elements into their projects" ON elements
    FOR INSERT WITH CHECK (
        page_id IN (
            SELECT p.id FROM pages p 
            JOIN projects pr ON p.project_id = pr.id 
            WHERE pr.user_id = auth.uid()
        )
    );

-- Policy for DELETE (users can delete elements from their projects)
CREATE POLICY "Users can delete elements from their projects" ON elements
    FOR DELETE USING (
        page_id IN (
            SELECT p.id FROM pages p 
            JOIN projects pr ON p.project_id = pr.id 
            WHERE pr.user_id = auth.uid()
        )
    );

-- Verification queries (run these to test the migration)
-- SELECT COUNT(*) FROM elements WHERE ai_generated = TRUE;
-- SELECT content FROM elements WHERE ai_generated = TRUE LIMIT 5;
-- \d elements; -- Shows table structure including new column